# Configuration file example
outdir: /home/felipe/new_test
dbname: /data/des/dblib/desdecade_lite_metadata.duckdb
date_start: 2013-10-25
date_end: 2013-12-31
np: 0
bands: [g, r, i, z]
coadd: True
finalcut: True
TAG: Y6A2
